-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 10 Şub 2019, 06:10:40
-- Sunucu sürümü: 10.1.37-MariaDB
-- PHP Sürümü: 7.3.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `again2`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `makaleler`
--

CREATE TABLE `makaleler` (
  `makale_id` int(11) NOT NULL,
  `makale_baslik` varchar(300) NOT NULL,
  `makale_icerik` text NOT NULL,
  `kullanici_id` int(11) NOT NULL,
  `goruntulenme_sayisi` int(11) NOT NULL,
  `begeni_sayisi` int(11) NOT NULL,
  `paylasim_zamani` date NOT NULL,
  `resim_linki` varchar(300) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Tablo döküm verisi `makaleler`
--

INSERT INTO `makaleler` (`makale_id`, `makale_baslik`, `makale_icerik`, `kullanici_id`, `goruntulenme_sayisi`, `begeni_sayisi`, `paylasim_zamani`, `resim_linki`) VALUES
(1, 'Bu Kısımda Baslik 1 Yer Alacak Uzunlugu Onemli Degil', 'The first strategy for learning the skills of change is self-knowledge. Self-knowledge is being aware of what one can do, how one can develop herself/himself or what her problem is about change.  When self-knowledge is thought, two major types of self-knowledge should come to minds, which are self-knowledge about failure and self-knowledge about capacity or capability. The first type of self-knowledge teaches one why s/he cannot change herself/ himself. If one knows that she does not have ability for doing something such as, passing exams, remembering telephone numbers or cooking, she will understand and solve her problems about it. Changing oneself is similar to solving these problems. Firstly, one should know why she cannot change, then, she can do the necessary activities for change. To illustrate, when a fat girl wants to be fitter, she should know why she is fat, whether she is responsible for this situation or not, she could be eating too much meat or drinking too much coke or coffee with too much sugar. After finding the causes of her situation, she may solve her problem which leads to be fitter, she can say that she changed then. Is this change? Of course, being different from her first appearance can also be included in content of change.     The second type of self-knowledge is about knowing own capacities and abilities. When one knows what she can do for changing or developing herself, she can be encouraged herself for being successful about change and limiting herself to do useful activities for change. This means that, is she has information about her abilities such as cooking, make up, reading book in different languages or diving, she may develop herself easily as she does not start any strategy which she cannot do to change or develop herself. Limiting herself doing what she cannot do may make her successful in the changing process.', 1, 7568, 6, '2019-02-07', 'data/images/doga.jpg'),
(2, 'Uzunlugu Onemli Olmayan Baslik 3 Buraya Gelecek', 'The second and the most important strategy for learning change is changing herself in two area. The first area of changing herself is mental change. This means that trusting herself in changing process. When one believes that she can change what she wants, this thought can motivate her starting to change. As the olders’ saying, starting is half of finishing. In addition to this, trusting herself for having ability for change may help her to be used to changes. When she is used to changes, change will be her life style. She will not stay at the same point after this process. She will want to develop herself frequently.  In addition to changing herself mentally, changing herself physically is also effective for learning the skills of change. Changing physically makes one stronger and happier. Being happier and stronger makes individuals more successful in change. When one trusts that her appearance is better than past, she will be fulfilled with passion for change. As a result of this (like self-knowledge about capacity) , one feels herself motivated for developing oneself. In addition to this, her lifestyle will change with her changes too.', 2, 7987654, 5380, '2019-02-05', 'data/images/doga2.jpg'),
(3, 'İngilizce Makale -3- Nuclear Energy Is Life', 'Giving a completely or partly form or appearance to something is called as change. Developing, growing or being older are several types of change. In these days,  it can be clearly seem that everything changes fast. To illustrate, the nature is damaged, people are less healthy and living is more difficult. For living in this world happily and safely, one must know she should obey this world’s rules. While the world is changing, one should change herself at the same time with it. This is true; however, do individuals of the world know how they can change themselves? Websites which include questions and chat forums about change show that especially young generation does not know clearly how they can be different. Since these websites are fulfilled with teenagers who ask about the strategies of change. One can learn the skills of change by watching two main strategies.', 3, 78965, 621461, '2019-02-05', 'data/images/doga4.jpg'),
(4, 'İngilizce Makale -2- TURKISH IS ENOUGH FOR US', 'Not only in these days, but also in the past, a country’s development level have been depend on its  level of education which is defined by Crawley and Ashby as teaching  somebody about things like reading, writing and mathematics at school or college  (1994, p. 106). In Turkey, after students finish high school, they start university where they learn their jobs efficiently.  During university years, youngs develop themselves and learn what they want. When this feature of universities’ is thought, there appear two types of schools. While students get their whole education in English in one of them, students get their education in their native language, Turkish, in other type. A result can be clearly seen that students should not be forced to study their departments in English in Turkey because of negative effects of English based education.', 4, 13523, 12349, '2019-02-07', 'data/images/doga3.jpg'),
(5, 'İngilizce Makale -1- How Can One Change?', 'To begin with, about the cost and stabelity sides of Nuclear power. When coal costs and usage in the past is thught, there will clearly appear that coal costs have been increasing by year by which makes people in a difficult stuation; however, nuclear power is not like coal or others. Firstly, nuclear power is the best source for our budget. Hw can i say this, certainly? There is a research about this subject, OECD study. There are thirteen countries which use whole types of energies in a year (2001), in this study. The rsult is so surprised me that there is a huge difference between nuclear power, coal and gas costs. To illustrate, in Belgium, nuclear power cost is 6.1 c/kWh while coal is 8.2 c/kWh and gas is 9.0 c/kWh. Morever, this difference is bigger in China is that while nuclear power cost is 3.6 c/kWh, coal is 5.5 c/kWh (table 4-1). These results show that nuclear energy is cheaper tha others therefore people can use it safely and easly for their nature and especially budget. Morover, nuclear power limits the electricity cost, that is, when people use different amounts electricity. In Finland, a research was done in 2003 about ths. Result of this research shows that there is  clear difference between nuclear powr and other types of energy. While gas is used, electricity price increases to 3.92; however, nuclear power decreases this price to 2.37. The most interesting result of the study is that wind using makes prices 5.01. Can you see the huge difference? Secondly, nuclear energy is stable ,that is, it is useful and safe for nature of human.  Marvin Fertel, the Nuclear Energy Institute’s Chef Nuclear Officer, in his talks about the Clean Air and Climate Change of the US, he says that they thought public health and safety . In addition to this, they try to avoid environment pollution. His statement is really absorbing that nuclear plants provides consumers and businesses with a high degree of forward prices stability.', 5, 12412, 65853, '2019-02-07', 'data/images/doga1.jfif'),
(6, 'Whatsapp Wweb Kullanımı', 'After the cost and stability sides of nuclear power, Comby says tht  an increasing number of environmentalists are now changing their minds about nuclear energy as there are good , solid, scentific and  environmental reasons to be in favor of nuclear energy. This is certainly true true as people will not use gas r coal, if they  think the huge disadvantages of  these energy sources. As people use too much the land needed by Earth to regulate it’s climate and cemistry. For example, a car consumes 10 to 30 times as much as its drivers; when we imagine the extra formland required to feed  the appetite of cars, this will be more complex. Lovelock says “…,  let us use the small input from renewables sensibly, but only one immediately avaible source does not cause global warng and that is nuclear energy. ”(2004, p.2)That is true because we use the natural gas instead of coal or oil releases, half of much carbondioxide forms. After nuclear power’s price , stable and environmental part, there is a good point for nuclear enery that science, that is nuclear energy is removable.', 6, 3457, 236, '2019-02-07', 'data/images/doga2.jfif'),
(7, 'Using English as instruction language in Turkey can help students', 'We can product  them in different and difficult conditions, too, since their source does not finish. In addition to this, NMD reports show that different amount of energy. For example, gas produces 39 mj/kg while uranium which is the main source of nuclear power produces 24.000.000 mj/kg. (Ünalan, 2008, p.3) Can you see the huge difference  between the energy sources? Science comes in this point. We can produce as a huge amount of energy from uranium. In addition to these points, nuclear energy can be used by using science for a country’s needs. To illustrate, China,the most crowded country in the World, plans it’s economy and energy sources. China plans to solve it’s energy problem by paying atention to nuclear energy. To do this, Chineese scientists have developed their nuclear power production technlogy. Morever, they say that thy will not need to any other source from nuclear energy  in 3000 years if they use nuclear energy plants. (“China tries to,” 2011)  Therefore, this shows people that nuclear energy should be used more efficiently.', 7, 2345, 328, '2019-02-07', 'data/images/doga3.jpg'),
(8, 'Not only in these days, but also in the past, a country’s development', 'Taking education in English forms different problems for university students.  The first problem for students is that they may lose their important senses due to their education language. They may lose their not only personal senses such that learning passion or self-confidence, but also their academic senses such that criticism or command abilities during their education life. When they get their subjects in English, they must do two difficult jobs simultaneously. While they listen and translate the topic which their instructor tell them, they should be able to understand what are the main points of the subject and where they should pay attention. As a result of this, they lose their passion for learning the subject. Moreover, they may lose their self-confidence since they may not follow the topic efficiently. That is, they may lose their attention to subject in lesson then they may not be able to catch the lecture again which can make them demoralized. For this reason, they can think that they would not pass the exam ad would fail it. Students may lose their valid academic senses due to their lecture language. In other words, they may not criticize the topic efficiently while they use English in their lecture hours continuously. As when one lose a main point of the topic, s/he may miss whole valid points of topic. Analyzing and criticizing abilities are born with command ability which makes the lessons more understandable for students.  Lack command ability may make a student be failed. “ Our clever students are lack of analyzing, commanding and criticizing abilities for Math, Physic or Chemistry lessons which need to command, criticism and analyses. “ (Demirören, 2002, p.1)', 8, 123, 126, '2019-02-07', 'data/images/doga3.jfif'),
(9, 'level have been depend on its  level of education which is defined by Crawley and Ashby as teaching  ', ' The rsult is so surprised me that there is a huge difference between nuclear power, coal and gas costs. To illustrate, in Belgium, nuclear power cost is 6.1 c/kWh while coal is 8.2 c/kWh and gas is 9.0 c/kWh. Morever, this difference is bigger in China is that while nuclear power cost is 3.6 c/kWh, coal is 5.5 c/kWh (table 4-1). These results show that nuclear energy is cheaper tha others therefore people can use it safely and easly for their nature and especially budget. Morover, nuclear power limits the electricity cost, that is, when people use different amounts electricity. In Finland, a research was done in 2003 about ths. Result of this research shows that there is  clear difference between nuclear powr and other types of energy. While gas is used, electricity price increases to 3.92; however, nuclear power decreases this price to 2.37. The most interesting result of the study is that wind using makes prices 5.01. Can you see the huge difference? ', 9, 85, 6792, '2019-02-10', 'data/images/doga5.jfif'),
(10, 'Türkçe Karakter Sorunuda Çözülmüş Oldu', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi? Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam corporis ex, omnis nulla esse hic quo voluptatibus? Ab suscipit aut vel inventore. Quasi soluta similique labore reiciendis fugit. Quidem, modi?', 10, 7124365, 362749, '2019-02-05', 'data/images/doga6.jfif'),
(11, 'İngilizce Makale Örnekleri Serisi Başlıyor…', 'and develop new things about her/his job if s/he gets education in her/his native language as people should know native terms of their jobs’ but also English versions.  Sinanoğlu thinks that a student can develop himself in his job and career life safely if he gets his education in his own language. (2006, p.12) Students may get English courses in their free times such as summer holidays or after lecture hours.\r\n\r\nIn conclusion, while English Based Education may help students in some ways, it has negative effects on students more. Due to its privative effects on students’ basic senses and learning process, English should not be the medium instruction language in Turkish universities.  Despite these applications, students should be oriented for applying language courses in summer ', 11, 11432, 5682, '2019-02-04', 'data/images/doga7.jfif'),
(12, 'cademic senses due to their lecture language. In other words, they may not criticize the topic efficiently while they use English in their l', 'That is, when they use English in their department continuously, they know English as Turkish too. However, when they do not write any essays in Turkish, Turkey may not achieve academic successes as students write their essays, reports, summaries and outlines in English while they think in Turkish. Not using Turkish in department lessons, they may forget grammar and basic concepts of Turkish and lose their ability of producing Turkish literatures. That is, when they use English in their department continuously, they know English as Turkish too. However, when they do not write any essays in Turkish, Turkey may not achieve academic successes as students write their essays, reports, summaries and outlines in English while they think in Turkish. Not using Turkish in department lessons, they may forget grammar and basic concepts of Turkish and lose their ability of producing Turkish literatures.', 12, 7832465, 782368, '2019-02-03', 'data/images/doga8.jfif'),
(13, 'Treating Heart Attack Patients More Speedly Through Lean', 'Another month, another story of a lean project told by the Siena hospital front-line folks. This time we take you to the Intensive Care Nursery, whose layout was transformed to provide better care to premature newborns.\r\n\r\nTo complete their neuromotor development, premature newborn infants need high-tech equipment, well-trained carers, and a quiet and sterile place. Our medical staff, who constantly monitors the newborns’ evolving condition, knows all too well how important a clean, safe environment and the support we can provide family members are to the little patients’ overall wellbeing.', 9, 783465, 672138, '2019-02-07', 'data/images/doga.jpg'),
(14, 'Changing the Layout of Nursery to Improve Neonatal Care in Siena University Hospital, Italy', 'John Shook and his former mentor Isao Yoshino first met at NUMMI in the 1980s, when Toyota had its first venture in the United States. Through NUMMI, the organization wanted to develop people outside Japan to achieve fantastic results in the US – and they succeeded. Isao was the person driving the training of Americans in Japan and John Shook the first American employed to support him. But what would John and Isao have done differently at NUMMI? \r\n\r\nThis is only one of the many topics the two recently discussed in Braga, Portugal at the European Lean Educator Conference. As I facilitated this discussion, I couldn’t help but think of the many opportunities that lean thinking can still afford us… and of all the things we still have to learn about it.', 10, 3247865, 1762537, '2019-02-04', 'data/images/doga2.jpg'),
(15, 'The formula behind the success of Toyota', 'I will let you read the book to find out what these elements are. For now, I will say the book is full of great insights and precious advice. It also happens to be a wonderful read, full of telling anecdotes that explain the nuts and bolts of Toyota culture.\r\n\r\nFor me, the biggest discovery was the role the lean practice of nemawashi – engaging everyone in getting to a solution – plays in creating the culture that supports Toyota. As an example, Tracey explains that, when she was coached on an A3, his coach would not only look at the result of the experiments and the disciplined thinking behind these, but also at how she managed to engage everyone in carrying out the experiment leading to the improvement.\r\n\r\nI was lucky enough to have the opportunity to ask Tracey and Ernie a few questions about their book. The full version of this interview can be found on my blog.\r\n\r\n', 3, 67235, 1278937, '2019-02-04', 'data/images/doga4.jpg'),
(16, 'VIDEO – In this video from the recent European Lean Educator Conference, John Shook and Isao Yoshino draw on their experience at Toyota to reflect on the development of lean thinkers.', 'Some in the business improvement world wonder whether or not we should still care about this old Toyota stuff, citing Agile as the “new thing”. Interestingly enough, we recently had the pleasure to have Isao at a seminar in Stockholm, which was attended by a lot of experienced Agile folks. They all agreed that Agile has its roots in lean thinking, and were in fact able to get many important insights from Isao – the most important one perhaps being that lean is about developing people and not implementing tools (still the prevalent approach in the Agile world). Lean thinking still has a lot to give the world!\r\n\r\nOk, I won’t share any more spoilers from the discussion between John and Isao. Instead, I will let you enjoy it in this video:\r\n\r\n', 1, 1762345, 176248, '2019-02-07', 'data/images/doga3.jpg');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `makaleler`
--
ALTER TABLE `makaleler`
  ADD PRIMARY KEY (`makale_id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `makaleler`
--
ALTER TABLE `makaleler`
  MODIFY `makale_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
